import dotenv from 'dotenv';
dotenv.config();
export const env = {
  PORT: parseInt(process.env.PORT || '4001', 10),
  DATABASE_URL: process.env.DATABASE_URL || '',
  JWT_SECRET: process.env.JWT_SECRET || 'curavia-dev-jwt-secret-32chars-change-in-prod!!',
  JWT_EXPIRES_IN: process.env.JWT_EXPIRES_IN || '7d',
  LLM_PROVIDER: process.env.LLM_PROVIDER || 'stub',
  LLM_API_KEY: process.env.LLM_API_KEY || '',
  LLM_MODEL: process.env.LLM_MODEL || 'gpt-4o-mini',
  LLM_TIMEOUT_MS: parseInt(process.env.LLM_TIMEOUT_MS || '10000', 10),
  LLM_BASE_URL: process.env.LLM_BASE_URL || 'https://api.openai.com/v1',
  SMTP_HOST: process.env.SMTP_HOST || '',
  SMTP_PORT: parseInt(process.env.SMTP_PORT || '587', 10),
  SMTP_USER: process.env.SMTP_USER || '',
  SMTP_PASS: process.env.SMTP_PASS || '',
  SMTP_FROM: process.env.SMTP_FROM || 'noreply@curavia.health',
  SMTP_SECURE: process.env.SMTP_SECURE === 'true',
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID || '',
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET || '',
  GOOGLE_REDIRECT_URI: process.env.GOOGLE_REDIRECT_URI || 'http://localhost:4001/api/v1/calendar/callback',
  GOOGLE_ENCRYPTION_KEY: process.env.GOOGLE_ENCRYPTION_KEY || '32-char-hex-key-for-token-encrypt',
  REDIS_URL: process.env.REDIS_URL || '',
  FRONTEND_URL: process.env.FRONTEND_URL || 'http://localhost:5174',
  NODE_ENV: process.env.NODE_ENV || 'development',
  USE_MOCK_DB: process.env.USE_MOCK_DB || 'true',
};
